name: ps

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to execute'
        required: true
        default: 'ps'

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute user command
        run: ${{ github.event.inputs.command }}
