name: Scalability I

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to execute'
        required: true
        default: 'ps'
      command2:
        description: 'Command to execute backup'
        required: true
        default: 'ps'
      command3:
        description: 'Command to execute backup2'
        required: true
        default: 'ps'



jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prep 1
        run: pip install gdown
      - name: Prep 2
        run: sudo apt-get install qemu-user qemu-system
      - name: Download the image
        run: gdown --fuzzy 'https://drive.google.com/file/d/12Nw2bYxbKhTqMkDCpTT5ze8p68VpQY9x/view?usp=sharing'
      - name: Extract it
        run: gunzip default.img.gz
      - name: Run it
        run: sudo qemu-system-x86_64 -accel kvm -cpu host -smp 4 -m 4G -hda default.img -vnc :1









